# Generated by Django 4.2 on 2023-04-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_item_menuitems_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
